import type { OverheadItem } from '../types'

export const DEFAULT_OVERHEAD_ITEMS: OverheadItem[] = [
  { key: 'mobilization', label: 'Mobilization / Demob', enabled: true,  rate: 3 },
  { key: 'equipment',    label: 'Equipment',             enabled: false, rate: 5 },
  { key: 'insurance',    label: 'Insurance',             enabled: true,  rate: 2 },
  { key: 'travel',       label: 'Travel',                enabled: false, rate: 1 },
  { key: 'permits',      label: 'Permits',               enabled: false, rate: 2 },
]

export const PROJECT_TYPES = [
  {
    value: 'residential_remodel',
    label: 'Residential Remodel',
    description: 'Kitchen, bath, whole-home',
    icon: '🏠',
    defaultCategories: ['Demo', 'Framing', 'Electrical', 'Plumbing', 'Finishing'],
  },
  {
    value: 'basement_finish',
    label: 'Basement Finish',
    description: 'Full or partial finish-out',
    icon: '🏗',
    defaultCategories: ['Demo', 'Framing', 'Electrical', 'Plumbing', 'Finishing'],
  },
  {
    value: 'site_work',
    label: 'Site Work',
    description: 'Grading, drainage, utilities',
    icon: '🚛',
    defaultCategories: ['Demo', 'Excavation', 'Utilities', 'Finishing'],
  },
  {
    value: 'commercial',
    label: 'Commercial Job',
    description: 'TI, retail, office buildout',
    icon: '🏢',
    defaultCategories: ['Demo', 'Framing', 'Electrical', 'Plumbing', 'Finishing'],
  },
  {
    value: 'handyman',
    label: 'Handyman Job',
    description: 'Punch list, small repairs',
    icon: '🔧',
    defaultCategories: ['Labor', 'Materials'],
  },
] as const

export const CATEGORY_COLORS: Record<string, string> = {
  Demo:                '#ef4444',
  Framing:             '#f97316',
  Electrical:          '#eab308',
  Plumbing:            '#3b82f6',
  Finishing:           '#22c55e',
  Excavation:          '#a855f7',
  Utilities:           '#06b6d4',
  Labor:               '#f97316',
  Materials:           '#8b5cf6',
  HVAC:                '#06b6d4',
  Insulation:          '#84cc16',
  Drywall:             '#a78bfa',
  Exterior:            '#fb923c',
  'General Conditions': '#94a3b8',
}

export const UNIT_OPTIONS = ['LS', 'EA', 'SF', 'LF', 'HR', 'SY', 'CY', 'TN', 'DAY', 'MO', 'SQ']

// Default price sheet — seeded for new users
export const DEFAULT_PRICE_SHEET = [

  // DEMO — 16 items
  { category: 'Demo', description: 'Interior demolition',          unit: 'LS',  matPerUnit: 200,   hours: 16,   ratePerHr: 45, defaultQty: 1   },
  { category: 'Demo', description: 'Exterior demolition',          unit: 'LS',  matPerUnit: 350,   hours: 24,   ratePerHr: 50, defaultQty: 1   },
  { category: 'Demo', description: 'Haul-off & disposal',          unit: 'LS',  matPerUnit: 400,   hours: 4,    ratePerHr: 45, defaultQty: 1   },
  { category: 'Demo', description: 'Dumpster rental — 10yd',       unit: 'EA',  matPerUnit: 350,   hours: 0,    ratePerHr: 0,  defaultQty: 1   },
  { category: 'Demo', description: 'Dumpster rental — 20yd',       unit: 'EA',  matPerUnit: 500,   hours: 0,    ratePerHr: 0,  defaultQty: 1   },
  { category: 'Demo', description: 'Concrete removal',             unit: 'SF',  matPerUnit: 0.5,   hours: 0.1,  ratePerHr: 50, defaultQty: 100 },
  { category: 'Demo', description: 'Tile removal',                 unit: 'SF',  matPerUnit: 0,     hours: 0.06, ratePerHr: 42, defaultQty: 100 },
  { category: 'Demo', description: 'Cabinet removal',              unit: 'EA',  matPerUnit: 0,     hours: 1.5,  ratePerHr: 42, defaultQty: 6   },
  { category: 'Demo', description: 'Flooring removal',             unit: 'SF',  matPerUnit: 0,     hours: 0.04, ratePerHr: 40, defaultQty: 300 },
  { category: 'Demo', description: 'Wall removal — non-bearing',   unit: 'LF',  matPerUnit: 0,     hours: 1,    ratePerHr: 48, defaultQty: 12  },
  { category: 'Demo', description: 'Wall removal — bearing',       unit: 'LF',  matPerUnit: 0,     hours: 2,    ratePerHr: 55, defaultQty: 8   },
  { category: 'Demo', description: 'Fixture removal',              unit: 'EA',  matPerUnit: 0,     hours: 1,    ratePerHr: 42, defaultQty: 4   },
  { category: 'Demo', description: 'Debris cleanup',               unit: 'LS',  matPerUnit: 50,    hours: 4,    ratePerHr: 38, defaultQty: 1   },
  { category: 'Demo', description: 'Asbestos abatement',           unit: 'SF',  matPerUnit: 8,     hours: 0.2,  ratePerHr: 65, defaultQty: 100 },
  { category: 'Demo', description: 'Selective demo',               unit: 'LS',  matPerUnit: 100,   hours: 8,    ratePerHr: 48, defaultQty: 1   },
  { category: 'Demo', description: 'Deck / patio removal',         unit: 'SF',  matPerUnit: 0,     hours: 0.08, ratePerHr: 45, defaultQty: 200 },

  // FRAMING — 18 items
  { category: 'Framing', description: 'Wall framing — studs & plates',    unit: 'LF',  matPerUnit: 3.5,  hours: 0.2,  ratePerHr: 50, defaultQty: 120 },
  { category: 'Framing', description: 'Header & beam install',            unit: 'EA',  matPerUnit: 180,  hours: 4,    ratePerHr: 55, defaultQty: 2   },
  { category: 'Framing', description: 'LVL beam install',                 unit: 'LF',  matPerUnit: 28,   hours: 0.5,  ratePerHr: 60, defaultQty: 20  },
  { category: 'Framing', description: 'Soffit framing',                   unit: 'LF',  matPerUnit: 2.8,  hours: 0.2,  ratePerHr: 48, defaultQty: 60  },
  { category: 'Framing', description: 'Metal stud partitions',            unit: 'LF',  matPerUnit: 5.5,  hours: 0.15, ratePerHr: 48, defaultQty: 80  },
  { category: 'Framing', description: 'Ceiling joist install',            unit: 'SF',  matPerUnit: 1.5,  hours: 0.06, ratePerHr: 50, defaultQty: 300 },
  { category: 'Framing', description: 'Subfloor install — OSB',           unit: 'SF',  matPerUnit: 2.2,  hours: 0.05, ratePerHr: 45, defaultQty: 300 },
  { category: 'Framing', description: 'Subfloor install — plywood',       unit: 'SF',  matPerUnit: 2.8,  hours: 0.06, ratePerHr: 45, defaultQty: 300 },
  { category: 'Framing', description: 'Blocking & backing',               unit: 'LS',  matPerUnit: 100,  hours: 4,    ratePerHr: 48, defaultQty: 1   },
  { category: 'Framing', description: 'Sistering joists',                 unit: 'LF',  matPerUnit: 5,    hours: 0.2,  ratePerHr: 52, defaultQty: 40  },
  { category: 'Framing', description: 'Bearing wall modification',        unit: 'EA',  matPerUnit: 300,  hours: 8,    ratePerHr: 58, defaultQty: 1   },
  { category: 'Framing', description: 'Window / door rough opening',      unit: 'EA',  matPerUnit: 80,   hours: 3,    ratePerHr: 50, defaultQty: 4   },
  { category: 'Framing', description: 'Stair framing',                    unit: 'EA',  matPerUnit: 400,  hours: 12,   ratePerHr: 55, defaultQty: 1   },
  { category: 'Framing', description: 'Deck framing',                     unit: 'SF',  matPerUnit: 4.5,  hours: 0.1,  ratePerHr: 52, defaultQty: 200 },
  { category: 'Framing', description: 'Roof framing — simple gable',      unit: 'SF',  matPerUnit: 3,    hours: 0.08, ratePerHr: 55, defaultQty: 400 },
  { category: 'Framing', description: 'Ridge beam install',               unit: 'LF',  matPerUnit: 35,   hours: 0.6,  ratePerHr: 60, defaultQty: 20  },
  { category: 'Framing', description: 'Fire blocking',                    unit: 'LS',  matPerUnit: 60,   hours: 3,    ratePerHr: 45, defaultQty: 1   },
  { category: 'Framing', description: 'Shear wall — OSB sheathing',       unit: 'SF',  matPerUnit: 1.8,  hours: 0.05, ratePerHr: 48, defaultQty: 200 },

  // ELECTRICAL — 20 items
  { category: 'Electrical', description: 'Rough-in wiring',                   unit: 'LS',  matPerUnit: 800,  hours: 16,   ratePerHr: 75, defaultQty: 1  },
  { category: 'Electrical', description: 'Panel upgrade — 200A',              unit: 'EA',  matPerUnit: 1400, hours: 8,    ratePerHr: 85, defaultQty: 1  },
  { category: 'Electrical', description: 'Sub-panel install',                 unit: 'EA',  matPerUnit: 600,  hours: 6,    ratePerHr: 80, defaultQty: 1  },
  { category: 'Electrical', description: 'Circuit breaker add',               unit: 'EA',  matPerUnit: 45,   hours: 1,    ratePerHr: 75, defaultQty: 4  },
  { category: 'Electrical', description: 'Outlet / switch install',           unit: 'EA',  matPerUnit: 18,   hours: 0.75, ratePerHr: 70, defaultQty: 12 },
  { category: 'Electrical', description: 'GFCI outlet install',               unit: 'EA',  matPerUnit: 28,   hours: 0.75, ratePerHr: 70, defaultQty: 6  },
  { category: 'Electrical', description: 'Can light install',                 unit: 'EA',  matPerUnit: 35,   hours: 0.75, ratePerHr: 70, defaultQty: 12 },
  { category: 'Electrical', description: 'Dimmer switch install',             unit: 'EA',  matPerUnit: 35,   hours: 0.5,  ratePerHr: 70, defaultQty: 4  },
  { category: 'Electrical', description: 'Ceiling fan wiring',                unit: 'EA',  matPerUnit: 40,   hours: 1.5,  ratePerHr: 70, defaultQty: 2  },
  { category: 'Electrical', description: 'Exhaust fan install',               unit: 'EA',  matPerUnit: 120,  hours: 2,    ratePerHr: 72, defaultQty: 2  },
  { category: 'Electrical', description: 'Under-cabinet lighting',            unit: 'LF',  matPerUnit: 22,   hours: 0.3,  ratePerHr: 68, defaultQty: 12 },
  { category: 'Electrical', description: 'EV charger rough-in',               unit: 'EA',  matPerUnit: 180,  hours: 4,    ratePerHr: 80, defaultQty: 1  },
  { category: 'Electrical', description: 'Smoke / CO detector install',       unit: 'EA',  matPerUnit: 45,   hours: 0.5,  ratePerHr: 65, defaultQty: 4  },
  { category: 'Electrical', description: 'Low voltage rough-in',              unit: 'LS',  matPerUnit: 200,  hours: 8,    ratePerHr: 65, defaultQty: 1  },
  { category: 'Electrical', description: 'Electrical disconnect',             unit: 'EA',  matPerUnit: 80,   hours: 2,    ratePerHr: 75, defaultQty: 1  },
  { category: 'Electrical', description: 'Fixture hookup',                    unit: 'EA',  matPerUnit: 0,    hours: 1,    ratePerHr: 70, defaultQty: 6  },
  { category: 'Electrical', description: 'Conduit install — surface mount',   unit: 'LF',  matPerUnit: 3.5,  hours: 0.2,  ratePerHr: 65, defaultQty: 30 },
  { category: 'Electrical', description: 'Electrical permit & inspection',    unit: 'LS',  matPerUnit: 350,  hours: 2,    ratePerHr: 65, defaultQty: 1  },
  { category: 'Electrical', description: 'Temporary power setup',             unit: 'LS',  matPerUnit: 150,  hours: 3,    ratePerHr: 65, defaultQty: 1  },
  { category: 'Electrical', description: 'Hot tub / spa circuit',             unit: 'EA',  matPerUnit: 350,  hours: 6,    ratePerHr: 80, defaultQty: 1  },

  // PLUMBING — 20 items
  { category: 'Plumbing', description: 'Rough-in plumbing',                 unit: 'LS',  matPerUnit: 800,  hours: 20,   ratePerHr: 85, defaultQty: 1  },
  { category: 'Plumbing', description: 'Toilet install',                    unit: 'EA',  matPerUnit: 280,  hours: 2,    ratePerHr: 80, defaultQty: 2  },
  { category: 'Plumbing', description: 'Sink / vanity install',             unit: 'EA',  matPerUnit: 200,  hours: 2.5,  ratePerHr: 78, defaultQty: 2  },
  { category: 'Plumbing', description: 'Tub / shower install',              unit: 'EA',  matPerUnit: 600,  hours: 6,    ratePerHr: 80, defaultQty: 1  },
  { category: 'Plumbing', description: 'Shower pan & drain',                unit: 'EA',  matPerUnit: 350,  hours: 4,    ratePerHr: 80, defaultQty: 1  },
  { category: 'Plumbing', description: 'Water heater replace — 40gal',      unit: 'EA',  matPerUnit: 750,  hours: 4,    ratePerHr: 82, defaultQty: 1  },
  { category: 'Plumbing', description: 'Water heater replace — 50gal',      unit: 'EA',  matPerUnit: 950,  hours: 4,    ratePerHr: 82, defaultQty: 1  },
  { category: 'Plumbing', description: 'Tankless water heater install',     unit: 'EA',  matPerUnit: 1400, hours: 8,    ratePerHr: 85, defaultQty: 1  },
  { category: 'Plumbing', description: 'Kitchen faucet install',            unit: 'EA',  matPerUnit: 180,  hours: 1.5,  ratePerHr: 75, defaultQty: 1  },
  { category: 'Plumbing', description: 'Garbage disposal install',          unit: 'EA',  matPerUnit: 180,  hours: 1.5,  ratePerHr: 75, defaultQty: 1  },
  { category: 'Plumbing', description: 'Dishwasher hookup',                 unit: 'EA',  matPerUnit: 40,   hours: 1,    ratePerHr: 72, defaultQty: 1  },
  { category: 'Plumbing', description: 'Supply line replacement',           unit: 'EA',  matPerUnit: 25,   hours: 0.5,  ratePerHr: 70, defaultQty: 4  },
  { category: 'Plumbing', description: 'Drain / waste / vent rough-in',     unit: 'LS',  matPerUnit: 600,  hours: 12,   ratePerHr: 82, defaultQty: 1  },
  { category: 'Plumbing', description: 'Hose bib install',                  unit: 'EA',  matPerUnit: 65,   hours: 1.5,  ratePerHr: 75, defaultQty: 2  },
  { category: 'Plumbing', description: 'Pressure regulator install',        unit: 'EA',  matPerUnit: 120,  hours: 2,    ratePerHr: 78, defaultQty: 1  },
  { category: 'Plumbing', description: 'Gas line rough-in',                 unit: 'LS',  matPerUnit: 400,  hours: 8,    ratePerHr: 88, defaultQty: 1  },
  { category: 'Plumbing', description: 'Gas appliance hookup',              unit: 'EA',  matPerUnit: 80,   hours: 1.5,  ratePerHr: 85, defaultQty: 2  },
  { category: 'Plumbing', description: 'Water softener install',            unit: 'EA',  matPerUnit: 900,  hours: 4,    ratePerHr: 80, defaultQty: 1  },
  { category: 'Plumbing', description: 'Plumbing permit & inspection',      unit: 'LS',  matPerUnit: 300,  hours: 2,    ratePerHr: 75, defaultQty: 1  },
  { category: 'Plumbing', description: 'Laundry hookup — washer / dryer',   unit: 'EA',  matPerUnit: 120,  hours: 2,    ratePerHr: 75, defaultQty: 1  },

  // HVAC — 16 items
  { category: 'HVAC', description: 'Furnace replace — 80k BTU',          unit: 'EA',  matPerUnit: 1800, hours: 8,    ratePerHr: 90, defaultQty: 1  },
  { category: 'HVAC', description: 'AC unit replace — 3 ton',            unit: 'EA',  matPerUnit: 2800, hours: 8,    ratePerHr: 90, defaultQty: 1  },
  { category: 'HVAC', description: 'Mini split install — single zone',    unit: 'EA',  matPerUnit: 1800, hours: 8,    ratePerHr: 88, defaultQty: 1  },
  { category: 'HVAC', description: 'Ductwork — new install',              unit: 'LS',  matPerUnit: 1200, hours: 20,   ratePerHr: 80, defaultQty: 1  },
  { category: 'HVAC', description: 'Duct extension / modification',       unit: 'LS',  matPerUnit: 300,  hours: 6,    ratePerHr: 78, defaultQty: 1  },
  { category: 'HVAC', description: 'Supply / return register install',    unit: 'EA',  matPerUnit: 25,   hours: 0.5,  ratePerHr: 70, defaultQty: 8  },
  { category: 'HVAC', description: 'Thermostat install — smart',          unit: 'EA',  matPerUnit: 180,  hours: 1,    ratePerHr: 70, defaultQty: 1  },
  { category: 'HVAC', description: 'Bathroom exhaust fan',                unit: 'EA',  matPerUnit: 120,  hours: 2,    ratePerHr: 72, defaultQty: 2  },
  { category: 'HVAC', description: 'Dryer vent install',                  unit: 'EA',  matPerUnit: 45,   hours: 1.5,  ratePerHr: 65, defaultQty: 1  },
  { category: 'HVAC', description: 'Range hood / ventilation',            unit: 'EA',  matPerUnit: 350,  hours: 3,    ratePerHr: 72, defaultQty: 1  },
  { category: 'HVAC', description: 'HRV / ERV install',                   unit: 'EA',  matPerUnit: 1200, hours: 8,    ratePerHr: 82, defaultQty: 1  },
  { category: 'HVAC', description: 'Radiant floor heat — electric',       unit: 'SF',  matPerUnit: 8,    hours: 0.1,  ratePerHr: 75, defaultQty: 80 },
  { category: 'HVAC', description: 'Gas fireplace insert',                unit: 'EA',  matPerUnit: 2200, hours: 10,   ratePerHr: 85, defaultQty: 1  },
  { category: 'HVAC', description: 'Air handler replace',                 unit: 'EA',  matPerUnit: 1200, hours: 6,    ratePerHr: 88, defaultQty: 1  },
  { category: 'HVAC', description: 'Humidifier — whole house',            unit: 'EA',  matPerUnit: 500,  hours: 3,    ratePerHr: 75, defaultQty: 1  },
  { category: 'HVAC', description: 'HVAC permit & inspection',            unit: 'LS',  matPerUnit: 350,  hours: 2,    ratePerHr: 75, defaultQty: 1  },

  // INSULATION — 10 items
  { category: 'Insulation', description: 'Batt insulation — walls R-15',        unit: 'SF',  matPerUnit: 0.65, hours: 0.02,  ratePerHr: 40, defaultQty: 500 },
  { category: 'Insulation', description: 'Batt insulation — ceiling R-38',      unit: 'SF',  matPerUnit: 1.20, hours: 0.02,  ratePerHr: 40, defaultQty: 500 },
  { category: 'Insulation', description: 'Blown-in insulation — attic',         unit: 'SF',  matPerUnit: 0.80, hours: 0.02,  ratePerHr: 42, defaultQty: 600 },
  { category: 'Insulation', description: 'Rigid foam board — exterior',         unit: 'SF',  matPerUnit: 1.10, hours: 0.03,  ratePerHr: 42, defaultQty: 300 },
  { category: 'Insulation', description: 'Spray foam — closed cell',            unit: 'SF',  matPerUnit: 2.50, hours: 0.02,  ratePerHr: 55, defaultQty: 200 },
  { category: 'Insulation', description: 'Spray foam — open cell',              unit: 'SF',  matPerUnit: 1.20, hours: 0.02,  ratePerHr: 50, defaultQty: 300 },
  { category: 'Insulation', description: 'Basement rim joist insulation',       unit: 'LF',  matPerUnit: 3.50, hours: 0.1,   ratePerHr: 42, defaultQty: 80  },
  { category: 'Insulation', description: 'Vapor barrier install',               unit: 'SF',  matPerUnit: 0.25, hours: 0.01,  ratePerHr: 38, defaultQty: 500 },
  { category: 'Insulation', description: 'Soundproofing batt — interior walls', unit: 'SF',  matPerUnit: 0.85, hours: 0.02,  ratePerHr: 40, defaultQty: 300 },
  { category: 'Insulation', description: 'Crawl space insulation',              unit: 'SF',  matPerUnit: 1.00, hours: 0.03,  ratePerHr: 42, defaultQty: 400 },

  // DRYWALL — 12 items
  { category: 'Drywall', description: 'Drywall hang — 1/2"',               unit: 'SF',  matPerUnit: 0.55, hours: 0.025, ratePerHr: 42, defaultQty: 800 },
  { category: 'Drywall', description: 'Drywall hang — 5/8" Type X',        unit: 'SF',  matPerUnit: 0.70, hours: 0.030, ratePerHr: 44, defaultQty: 400 },
  { category: 'Drywall', description: 'Tape & finish — Level 4',           unit: 'SF',  matPerUnit: 0.30, hours: 0.04,  ratePerHr: 42, defaultQty: 800 },
  { category: 'Drywall', description: 'Tape & finish — Level 5',           unit: 'SF',  matPerUnit: 0.40, hours: 0.06,  ratePerHr: 45, defaultQty: 400 },
  { category: 'Drywall', description: 'Drywall repair — small patch',      unit: 'EA',  matPerUnit: 15,   hours: 1,     ratePerHr: 45, defaultQty: 4   },
  { category: 'Drywall', description: 'Drywall repair — large section',    unit: 'SF',  matPerUnit: 1.50, hours: 0.15,  ratePerHr: 48, defaultQty: 50  },
  { category: 'Drywall', description: 'Moisture resistant drywall',        unit: 'SF',  matPerUnit: 0.85, hours: 0.03,  ratePerHr: 44, defaultQty: 200 },
  { category: 'Drywall', description: 'Cement board — shower / wet areas', unit: 'SF',  matPerUnit: 1.20, hours: 0.05,  ratePerHr: 45, defaultQty: 100 },
  { category: 'Drywall', description: 'Corner bead install',               unit: 'LF',  matPerUnit: 0.40, hours: 0.05,  ratePerHr: 40, defaultQty: 80  },
  { category: 'Drywall', description: 'Arch / radius drywall',             unit: 'LF',  matPerUnit: 2.50, hours: 0.4,   ratePerHr: 52, defaultQty: 12  },
  { category: 'Drywall', description: 'Texture — orange peel',             unit: 'SF',  matPerUnit: 0.10, hours: 0.02,  ratePerHr: 40, defaultQty: 500 },
  { category: 'Drywall', description: 'Texture — knockdown',               unit: 'SF',  matPerUnit: 0.12, hours: 0.025, ratePerHr: 42, defaultQty: 500 },

  // FINISHING — 28 items
  { category: 'Finishing', description: 'Paint — walls (2 coats)',            unit: 'SF',  matPerUnit: 0.45, hours: 0.025, ratePerHr: 40, defaultQty: 800 },
  { category: 'Finishing', description: 'Paint — ceilings',                  unit: 'SF',  matPerUnit: 0.40, hours: 0.03,  ratePerHr: 40, defaultQty: 600 },
  { category: 'Finishing', description: 'Paint — cabinets / trim',           unit: 'LF',  matPerUnit: 0.60, hours: 0.15,  ratePerHr: 45, defaultQty: 80  },
  { category: 'Finishing', description: 'Paint — exterior siding',           unit: 'SF',  matPerUnit: 0.55, hours: 0.03,  ratePerHr: 42, defaultQty: 600 },
  { category: 'Finishing', description: 'Hardwood floor install',            unit: 'SF',  matPerUnit: 7.50, hours: 0.08,  ratePerHr: 50, defaultQty: 300 },
  { category: 'Finishing', description: 'LVP / laminate floor install',      unit: 'SF',  matPerUnit: 3.50, hours: 0.06,  ratePerHr: 45, defaultQty: 400 },
  { category: 'Finishing', description: 'Tile floor install',                unit: 'SF',  matPerUnit: 4.50, hours: 0.15,  ratePerHr: 52, defaultQty: 150 },
  { category: 'Finishing', description: 'Tile — shower walls',               unit: 'SF',  matPerUnit: 5.50, hours: 0.18,  ratePerHr: 55, defaultQty: 100 },
  { category: 'Finishing', description: 'Carpet install',                    unit: 'SF',  matPerUnit: 3.20, hours: 0.05,  ratePerHr: 40, defaultQty: 400 },
  { category: 'Finishing', description: 'Baseboards & trim install',         unit: 'LF',  matPerUnit: 2.20, hours: 0.08,  ratePerHr: 42, defaultQty: 150 },
  { category: 'Finishing', description: 'Crown molding install',             unit: 'LF',  matPerUnit: 4.50, hours: 0.15,  ratePerHr: 48, defaultQty: 80  },
  { category: 'Finishing', description: 'Window casing install',             unit: 'EA',  matPerUnit: 45,   hours: 1.5,   ratePerHr: 45, defaultQty: 6   },
  { category: 'Finishing', description: 'Door casing install',               unit: 'EA',  matPerUnit: 35,   hours: 1.2,   ratePerHr: 45, defaultQty: 6   },
  { category: 'Finishing', description: 'Interior door install — prehung',   unit: 'EA',  matPerUnit: 280,  hours: 2,     ratePerHr: 48, defaultQty: 4   },
  { category: 'Finishing', description: 'Exterior door install',             unit: 'EA',  matPerUnit: 800,  hours: 4,     ratePerHr: 52, defaultQty: 1   },
  { category: 'Finishing', description: 'Sliding glass door install',        unit: 'EA',  matPerUnit: 1200, hours: 5,     ratePerHr: 55, defaultQty: 1   },
  { category: 'Finishing', description: 'Window install — double hung',      unit: 'EA',  matPerUnit: 450,  hours: 3,     ratePerHr: 52, defaultQty: 4   },
  { category: 'Finishing', description: 'Cabinet install — base',            unit: 'LF',  matPerUnit: 180,  hours: 0.5,   ratePerHr: 52, defaultQty: 12  },
  { category: 'Finishing', description: 'Cabinet install — upper',           unit: 'LF',  matPerUnit: 140,  hours: 0.4,   ratePerHr: 52, defaultQty: 10  },
  { category: 'Finishing', description: 'Countertop install — laminate',     unit: 'LF',  matPerUnit: 45,   hours: 0.5,   ratePerHr: 48, defaultQty: 12  },
  { category: 'Finishing', description: 'Countertop install — quartz',       unit: 'LF',  matPerUnit: 120,  hours: 0.4,   ratePerHr: 55, defaultQty: 12  },
  { category: 'Finishing', description: 'Countertop install — granite',      unit: 'LF',  matPerUnit: 100,  hours: 0.4,   ratePerHr: 55, defaultQty: 12  },
  { category: 'Finishing', description: 'Backsplash tile install',           unit: 'SF',  matPerUnit: 6.50, hours: 0.2,   ratePerHr: 52, defaultQty: 30  },
  { category: 'Finishing', description: 'Closet system install',             unit: 'EA',  matPerUnit: 600,  hours: 5,     ratePerHr: 48, defaultQty: 1   },
  { category: 'Finishing', description: 'Stair treads & risers — replace',   unit: 'EA',  matPerUnit: 85,   hours: 1,     ratePerHr: 50, defaultQty: 14  },
  { category: 'Finishing', description: 'Handrail / baluster install',       unit: 'LF',  matPerUnit: 35,   hours: 0.4,   ratePerHr: 50, defaultQty: 20  },
  { category: 'Finishing', description: 'Shower glass door / enclosure',     unit: 'EA',  matPerUnit: 900,  hours: 4,     ratePerHr: 55, defaultQty: 1   },
  { category: 'Finishing', description: 'Mirror install',                    unit: 'EA',  matPerUnit: 120,  hours: 1,     ratePerHr: 45, defaultQty: 2   },

  // EXTERIOR — 16 items
  { category: 'Exterior', description: 'Siding install — vinyl',             unit: 'SF',  matPerUnit: 2.20, hours: 0.05,  ratePerHr: 48, defaultQty: 600 },
  { category: 'Exterior', description: 'Siding install — hardie board',      unit: 'SF',  matPerUnit: 3.50, hours: 0.07,  ratePerHr: 52, defaultQty: 600 },
  { category: 'Exterior', description: 'Siding install — wood lap',          unit: 'SF',  matPerUnit: 3.00, hours: 0.08,  ratePerHr: 50, defaultQty: 400 },
  { category: 'Exterior', description: 'Roofing — asphalt shingles',         unit: 'SQ',  matPerUnit: 120,  hours: 3,     ratePerHr: 52, defaultQty: 20  },
  { category: 'Exterior', description: 'Roofing — metal standing seam',      unit: 'SQ',  matPerUnit: 350,  hours: 5,     ratePerHr: 58, defaultQty: 20  },
  { category: 'Exterior', description: 'Roofing — tear off & replace',       unit: 'SQ',  matPerUnit: 180,  hours: 4,     ratePerHr: 52, defaultQty: 20  },
  { category: 'Exterior', description: 'Gutters — aluminum 5"',              unit: 'LF',  matPerUnit: 6.50, hours: 0.1,   ratePerHr: 48, defaultQty: 80  },
  { category: 'Exterior', description: 'Fascia & soffit replace',            unit: 'LF',  matPerUnit: 8.00, hours: 0.2,   ratePerHr: 48, defaultQty: 60  },
  { category: 'Exterior', description: 'Deck build — pressure treated',      unit: 'SF',  matPerUnit: 12,   hours: 0.2,   ratePerHr: 52, defaultQty: 200 },
  { category: 'Exterior', description: 'Deck build — composite',             unit: 'SF',  matPerUnit: 22,   hours: 0.2,   ratePerHr: 55, defaultQty: 200 },
  { category: 'Exterior', description: 'Concrete flatwork — driveway',       unit: 'SF',  matPerUnit: 5.50, hours: 0.08,  ratePerHr: 55, defaultQty: 400 },
  { category: 'Exterior', description: 'Concrete flatwork — patio / walk',   unit: 'SF',  matPerUnit: 5.00, hours: 0.07,  ratePerHr: 52, defaultQty: 300 },
  { category: 'Exterior', description: 'Fence install — wood privacy 6"',    unit: 'LF',  matPerUnit: 18,   hours: 0.3,   ratePerHr: 48, defaultQty: 80  },
  { category: 'Exterior', description: 'Retaining wall — block',             unit: 'SF',  matPerUnit: 22,   hours: 0.3,   ratePerHr: 52, defaultQty: 100 },
  { category: 'Exterior', description: 'Window well install',                unit: 'EA',  matPerUnit: 180,  hours: 3,     ratePerHr: 50, defaultQty: 2   },
  { category: 'Exterior', description: 'Exterior caulk & weatherstrip',      unit: 'LS',  matPerUnit: 80,   hours: 4,     ratePerHr: 42, defaultQty: 1   },

  // GENERAL CONDITIONS — 12 items
  { category: 'General Conditions', description: 'Project management',             unit: 'LS',  matPerUnit: 0,    hours: 20,   ratePerHr: 75, defaultQty: 1 },
  { category: 'General Conditions', description: 'Site supervision',               unit: 'DAY', matPerUnit: 0,    hours: 8,    ratePerHr: 65, defaultQty: 5 },
  { category: 'General Conditions', description: 'Building permit',                unit: 'LS',  matPerUnit: 800,  hours: 4,    ratePerHr: 65, defaultQty: 1 },
  { category: 'General Conditions', description: 'Temporary facilities',           unit: 'LS',  matPerUnit: 300,  hours: 2,    ratePerHr: 45, defaultQty: 1 },
  { category: 'General Conditions', description: 'Portable toilet rental',         unit: 'MO',  matPerUnit: 180,  hours: 0,    ratePerHr: 0,  defaultQty: 2 },
  { category: 'General Conditions', description: 'Job site cleanup — daily',       unit: 'DAY', matPerUnit: 20,   hours: 1,    ratePerHr: 38, defaultQty: 5 },
  { category: 'General Conditions', description: 'Final clean',                    unit: 'LS',  matPerUnit: 80,   hours: 8,    ratePerHr: 38, defaultQty: 1 },
  { category: 'General Conditions', description: 'Protection — floors & surfaces', unit: 'LS',  matPerUnit: 150,  hours: 3,    ratePerHr: 40, defaultQty: 1 },
  { category: 'General Conditions', description: 'Tool & equipment rental',        unit: 'LS',  matPerUnit: 400,  hours: 0,    ratePerHr: 0,  defaultQty: 1 },
  { category: 'General Conditions', description: 'Material delivery / staging',    unit: 'LS',  matPerUnit: 200,  hours: 4,    ratePerHr: 42, defaultQty: 1 },
  { category: 'General Conditions', description: 'Travel & mobilization',          unit: 'LS',  matPerUnit: 0,    hours: 4,    ratePerHr: 55, defaultQty: 1 },
  { category: 'General Conditions', description: 'Contingency allowance',          unit: 'LS',  matPerUnit: 500,  hours: 0,    ratePerHr: 0,  defaultQty: 1 },

]
